### ISSUE TITLE
[Bug] guisp not supported?

### ISSUE THREAD

**Issue by ray-x** [jacoborus/estilo#52]
I followed instructions to migrate my color scheme to master. But the master branch failed to render guisp.

e.g.
It looks like this:
```
hi IncSearch guifg=NONE ctermfg=NONE guibg=#57109a ctermbg=54 gui=Bold,undercurl,Italic cterm=Bold,undercurl,Italic guisp=
```
It used to be like this:
```
hi IncSearch guifg=NONE ctermfg=NONE guibg=#57109a ctermbg=54 gui=bold,undercurl,italic cterm=bold,undercurl,italic guisp=#ecc48d
```

Anything needed to change for guisp?

**Comment by jacoborus** [comment]
@SiddharthShyniben that was exactly the problem, I just added your fix here: https://github.com/jacoborus/estilo/commit/6af35d21ec41137accb6f3a6b88be54c9425c7e1 thanks. Next time you can send a pull request ;)

@ray-x  it should be fixed now

**Comment by ray-x** [comment]
Thanks, But I am having the following errors after I update to the latest master.
Do I miss something?

```
error: Eta Error: Bad template syntax

Invalid or unexpected token
===========================
var tR='',__l,__lP,include=E.include.bind(E),includeFile=E.includeFile.bind(E)
function layout(p,d){__l=p;__lP=d}
tR+='""\n" Colorscheme: '
info.name
if(it.info.description) {
tR+='" Description: '
tR+=E.e(it.info.description)
}
if(it.info.url){
tR+='" URL: '
tR+=E.e(it.info.url)
}
if(it.info.author){
tR+='" Author: '
tR+=E.e(it.info.author)
}
if(it.info.license){
tR+='" License: '
tR+=E.e(it.info.license)
}
tR+='""\n\nset background='
tR+=E.e(it.info.background)
tR+='hi clear\nif exists("syntax_on")\n  syntax reset\nendif\nlet g:colors_name="'
tR+=E.e(it.info.name)
tR+='"\n\n\nlet Italic = ""\nif exists(\'g:'
tR+=E.e(it.info.name)
tR+='_italic\')\n  let Italic = "italic"\nendif\nlet g:'
tR+=E.e(it.info.name)
tR+='_italic = get(g:, \''
tR+=E.e(it.info.name)
tR+='_italic\', 0)\n\nlet Bold = ""\nif exists(\'g:'
tR+=E.e(info.name)
tR+='_bold\')\n  let Bold = "bold"\nendif\n\nlet g:'
tR+=E.e(it.info.name)
tR+='_bold = get(g:, \''
info.name
tR+='_bold\', 0)\n\n'
Object.keys(it.stacks).forEach(function (key) {
tR+='  '
const { link, fore, back, ui, guisp } = it.stacks[key];
tR+='  '
if(link){
tR+='hi link '
tR+=E.e(key)
tR+=' '
tR+=E.e(link)
tR+='  '
} else {
tR+='hi '
@key
tR+='    '
if(fore){
tR+=' guifg='
fore.hex
tR+=' ctermfg='
tR+=E.e(fore.xterm)
}
tR+='    '
if(back){
tR+=' guibg='
back.hex
tR+=' ctermbg='
tR+=E.e(back.xterm)
}
tR+='    '
if(ui){
tR+=' gui='
tR+=E.e(ui)
tR+=' cterm='
tR+=E.e(ui)
tR+=' '
}
tR+='    '
if(guisp){
tR+=' guisp='
tR+=E.e(guisp[0])
}
tR+='  '
}
tR+='\n'
})
tR+='\n'
if(term.color_0){
tR+='if has(\'terminal\')\n  let g:terminal_ansi_colors = [\n  \\ "'
tR+=E.e(term.color_0)
tR+='",\n  \\ "'
tR+=E.e(term.color_1)
tR+='",\n  \\ "'
tR+=E.e(term.color_2)
tR+='",\n  \\ "'
tR+=E.e(term.color_3)
tR+='",\n  \\ "'
tR+=E.e(term.color_4)
tR+='",\n  \\ "'
tR+=E.e(term.color_5)
tR+='",\n  \\ "'
tR+=E.e(term.color_6)
tR+='",\n  \\ "'
tR+=E.e(term.color_7)
tR+='",\n  \\ "'
tR+=E.e(term.color_8)
tR+='",\n  \\ "'
tR+=E.e(term.color_9)
tR+='",\n  \\ "'
tR+=E.e(term.color_10)
tR+='",\n  \\ "'
tR+=E.e(term.color_11)
tR+='",\n  \\ "'
tR+=E.e(term.color_12)
tR+='",\n  \\ "'
tR+=E.e(term.color_13)
tR+='",\n  \\ "'
tR+=E.e(term.color_14)
tR+='",\n  \\ "'
tR+=E.e(term.color_15)
tR+='"\n  \\ ]\nendif\n\nif has(\'nvim\')\n'
Object.keys(it.term).forEach(function (key) {
tR+='  let g:terminal_'
tR+=E.e(key)
tR+=' = "'
tR+=E.e(it.term[key])
tR+='"\n'
})
tR+='endif\n'
}
if(__l)tR=includeFile(__l,Object.assign(it,{body:tR},__lP))
if(cb){cb(null,tR)} return tR

    at EtaErr (file://$deno$/bundle.js:61:17)
    at compile (file://$deno$/bundle.js:394:19)
    at handleCache1 (file://$deno$/bundle.js:1936:70)
    at render (file://$deno$/bundle.js:1967:16)
    at renderColorscheme (file://$deno$/bundle.js:11444:18)
    at renderProject (file://$deno$/bundle.js:11597:32)
    at Command.fn (file://$deno$/bundle.js:11667:5)
    at Command.execute (file://$deno$/bundle.js:7032:24)
    at Command.parse (file://$deno$/bundle.js:6973:35)
    at async Command.parse (file://$deno$/bundle.js:6937:24)

```

**Comment by jacoborus** [comment]
I just pushed a new version, can you try again please?

**Comment by SiddharthShyniben** [comment]
@jacoborus ah i should have, i was so busy and I wasnt really sure whether that was the fix.
