### ISSUE TITLE
bug: `Deno.setRaw is not a function`

### ISSUE THREAD

**Issue by pjalsGit** [jacoborus/estilo#56]
I tried making a project with `estilo` but it errored with:
```
? Project name: (interstellar) › error: Uncaught (in promise) TypeError: Deno.setRaw is not a function
    at Input.#readChar (https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:13255:18)
    at Input.#readKey (https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:13248:42)
    at Input.read (https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:13200:47)
    at Input.#execute (https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:13157:25)
    at async Input.prompt (https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:13143:20)
    at async PromptList.runPrompt (https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:14264:45)
    at async https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:14196:17
    at async PromptList.runBeforeHook (https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:14252:9)
    at async PromptList.next (https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:14194:13)
    at async PromptList.run (https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:14189:9)
```

note that I have no idea how to make a VIM colorscheme, so this is kinda the only option!

**Comment by jacoborus** [comment]
I forgot to add the `--unstable` flag to the docs. Can you try again with it?
```sh
deno install --unstable --allow-read --allow-write -n estilo https://denopkg.com/jacoborus/estilo/dist/estilo.js
```
