### ISSUE TITLE
Estilo bug

### ISSUE THREAD

**Issue by saom88n** [jacoborus/estilo#59]
Error message :
```js
? Project name: (scheme) › error: Uncaught (in promise) TypeError: Deno.setRaw is not a function
            Deno.setRaw(Deno.stdin.rid, true, {
                 ^
    at Input.#readChar (https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:3797:18)
    at Input.#readKey (https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:3790:42)
    at Input.read (https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:3742:47)
    at Input.#execute (https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:3699:25)
    at async Input.prompt (https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:3685:20)
    at async PromptList.runPrompt (https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:4809:45)
    at async https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:4741:17
    at async PromptList.runBeforeHook (https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:4797:9)
    at async PromptList.next (https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:4739:13)
    at async PromptList.run (https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:4734:9)
```
```js
estilo : 2.0.0-beta.3
shell : fish, version 3.5.1
deno : 1.26.2
os : macOS 12.5.1 21G83 x86_64
kernel : 21.6.0
```

**Comment by jacoborus** [comment]
@saom88n fixed in 284cb639b3118a56290d01933a94d3ae37079d74
